notify:
  description: QQ邮件通知提醒
  fields:
    email:
      description: 【非必填】如果不填，发送给自己
      example: '635147515@qq.com'
    title:
      description: 【必填】邮件标题
      example: '邮件标题'
    message:
      description: 【非必填】要提醒的文字（可以为HTML格式和使用系统模板）
      example: '<b>当前时间： {{now()}} </b>'
    entity:
      description: 【非必填】实体列表，多个实体以英文逗号分隔（支持yaml列表格式）
      example: 'device_tracker.wo_de_shou_ji,media_player.ha_cloud_music'
    action:
      description: 【非必填】要执行的脚本或自动化实体，多个实体以英文逗号分隔（支持yaml列表格式）
      example: 'automation.gong_jiao_dao_zhan_bo_bao, script.1577623933610'